SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- 批量创建缺失的表 - 让前端所有页面都能正常加载
-- ============================================================

-- 1. 维保工单
CREATE TABLE IF NOT EXISTS work_orders (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_no VARCHAR(64) DEFAULT NULL COMMENT '工单编号',
  order_type INT DEFAULT 1 COMMENT '工单类型',
  device_name VARCHAR(128) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  unit_name VARCHAR(128) DEFAULT NULL,
  fault_desc TEXT DEFAULT NULL,
  priority INT DEFAULT 1,
  status INT DEFAULT 0 COMMENT '0待处理 1处理中 2已完成',
  assignee_name VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id), INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维保工单';

-- 2. 维保记录
CREATE TABLE IF NOT EXISTS maint_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  record_no VARCHAR(64) DEFAULT NULL,
  order_id BIGINT DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  result VARCHAR(16) DEFAULT NULL,
  cost DECIMAL(10,2) DEFAULT NULL,
  executor VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维保记录';

-- 3. 维保合同
CREATE TABLE IF NOT EXISTS maint_contracts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  contract_no VARCHAR(64) DEFAULT NULL,
  company_name VARCHAR(128) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  amount DECIMAL(12,2) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维保合同';

-- 4. 维保单位
CREATE TABLE IF NOT EXISTS maint_companies (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  company_name VARCHAR(128) DEFAULT NULL,
  contact VARCHAR(64) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  address VARCHAR(256) DEFAULT NULL,
  qualification VARCHAR(128) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维保单位';

-- 5. 巡检计划
CREATE TABLE IF NOT EXISTS patrol_plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plan_name VARCHAR(128) DEFAULT NULL,
  patrol_type INT DEFAULT 1,
  responsible_name VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  status INT DEFAULT 1,
  frequency VARCHAR(32) DEFAULT 'daily',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检计划';

-- 6. 巡检记录
CREATE TABLE IF NOT EXISTS patrol_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  patrol_no VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  unit_name VARCHAR(128) DEFAULT NULL,
  patrol_user_name VARCHAR(64) DEFAULT NULL,
  result INT DEFAULT 1,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='巡检记录';

-- 7. 隐患管理
CREATE TABLE IF NOT EXISTS hazards (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  hazard_no VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  unit_name VARCHAR(128) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  level INT DEFAULT 1,
  status INT DEFAULT 0,
  rectification TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id), INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='隐患管理';

-- 8. 应急预案
CREATE TABLE IF NOT EXISTS plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  plan_no VARCHAR(64) DEFAULT NULL,
  name VARCHAR(128) DEFAULT NULL,
  type VARCHAR(32) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应急预案';

-- 9. 演练记录
CREATE TABLE IF NOT EXISTS drills (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drill_no VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  unit_name VARCHAR(128) DEFAULT NULL,
  drill_date DATE DEFAULT NULL,
  drill_type VARCHAR(64) DEFAULT NULL,
  participants INT DEFAULT 0,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='演练记录';

-- 10. 演练参与人员
CREATE TABLE IF NOT EXISTS drill_participants (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  drill_id BIGINT DEFAULT NULL,
  name VARCHAR(64) DEFAULT NULL,
  role VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_drill_id (drill_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='演练参与人员';

-- 11. 消防检查
CREATE TABLE IF NOT EXISTS inspections (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inspect_no VARCHAR(64) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  unit_name VARCHAR(128) DEFAULT NULL,
  inspect_type INT DEFAULT 1,
  inspector VARCHAR(64) DEFAULT NULL,
  result INT DEFAULT 1,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消防检查';

-- 12. 检查项目
CREATE TABLE IF NOT EXISTS inspection_items (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  inspection_id BIGINT DEFAULT NULL,
  item_name VARCHAR(128) DEFAULT NULL,
  standard VARCHAR(256) DEFAULT NULL,
  result INT DEFAULT 1,
  remark TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_inspection_id (inspection_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检查项目';

-- 13. 知识库文档
CREATE TABLE IF NOT EXISTS documents (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) DEFAULT NULL,
  category VARCHAR(64) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  view_count INT DEFAULT 0,
  attachments JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='知识库文档';

-- 14. 文档分类
CREATE TABLE IF NOT EXISTS doc_categories (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) DEFAULT NULL,
  parent_id BIGINT DEFAULT 0,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档分类';

-- 15. 通知
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  type VARCHAR(32) DEFAULT 'system',
  recipient_id VARCHAR(64) DEFAULT NULL,
  is_read TINYINT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_recipient (recipient_id), INDEX idx_is_read (is_read)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通知';

-- 16. 值班排班
CREATE TABLE IF NOT EXISTS duty_schedules (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  schedule_no VARCHAR(64) DEFAULT NULL,
  user_id VARCHAR(64) DEFAULT NULL,
  user_name VARCHAR(64) DEFAULT NULL,
  duty_date DATE DEFAULT NULL,
  shift_id BIGINT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id), INDEX idx_duty_date (duty_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='值班排班';

-- 17. 值班日志
CREATE TABLE IF NOT EXISTS duty_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  log_no VARCHAR(64) DEFAULT NULL,
  schedule_id BIGINT DEFAULT NULL,
  user_id VARCHAR(64) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  events TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_schedule_id (schedule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='值班日志';

-- 18. 接警处置
CREATE TABLE IF NOT EXISTS dispatch_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  dispatch_no VARCHAR(64) DEFAULT NULL,
  alarm_id BIGINT DEFAULT NULL,
  handler VARCHAR(64) DEFAULT NULL,
  result TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alarm_id (alarm_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='接警处置记录';

-- 19. 班次
CREATE TABLE IF NOT EXISTS duty_shifts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  shift_name VARCHAR(64) DEFAULT NULL,
  start_time TIME DEFAULT NULL,
  end_time TIME DEFAULT NULL,
  description TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='班次';

-- 20. 交接班
CREATE TABLE IF NOT EXISTS duty_handovers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  handover_no VARCHAR(64) DEFAULT NULL,
  from_user_id VARCHAR(64) DEFAULT NULL,
  to_user_id VARCHAR(64) DEFAULT NULL,
  shift_id BIGINT DEFAULT NULL,
  content TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_from_user (from_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交接班记录';

-- 21. 系统日志
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  level VARCHAR(16) DEFAULT 'info',
  module VARCHAR(64) DEFAULT NULL,
  action VARCHAR(64) DEFAULT NULL,
  user_id VARCHAR(64) DEFAULT NULL,
  username VARCHAR(64) DEFAULT NULL,
  ip VARCHAR(64) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_level (level), INDEX idx_module (module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统日志';

-- 22. 建筑平面图
CREATE TABLE IF NOT EXISTS floor_plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  building_id VARCHAR(64) DEFAULT NULL,
  floor_id VARCHAR(64) DEFAULT NULL,
  name VARCHAR(128) DEFAULT NULL,
  image_url VARCHAR(512) DEFAULT NULL,
  scale DECIMAL(10,4) DEFAULT 1,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_building_id (building_id), INDEX idx_floor_id (floor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='建筑平面图';

-- 23. 报表
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  report_name VARCHAR(128) DEFAULT NULL,
  report_type VARCHAR(32) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  params JSON DEFAULT NULL,
  file_url VARCHAR(512) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表';

-- 24. 报表模板
CREATE TABLE IF NOT EXISTS report_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  template_name VARCHAR(128) DEFAULT NULL,
  template_type VARCHAR(32) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报表模板';

-- 25. 大屏配置
CREATE TABLE IF NOT EXISTS screen_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  screen_name VARCHAR(128) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='大屏配置';

-- 26. 大屏组件
CREATE TABLE IF NOT EXISTS screen_widgets (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  screen_id BIGINT DEFAULT NULL,
  widget_type VARCHAR(32) DEFAULT NULL,
  config JSON DEFAULT NULL,
  position JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_screen_id (screen_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='大屏组件';

-- 27. 培训
CREATE TABLE IF NOT EXISTS training_courses (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  course_name VARCHAR(128) DEFAULT NULL,
  course_type INT DEFAULT 1,
  duration INT DEFAULT 0,
  content TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='培训课程';

CREATE TABLE IF NOT EXISTS training_exams (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_name VARCHAR(128) DEFAULT NULL,
  pass_score INT DEFAULT 60,
  duration INT DEFAULT 30,
  questions JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='培训考试';

CREATE TABLE IF NOT EXISTS training_scores (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  exam_id BIGINT DEFAULT NULL,
  user_id VARCHAR(64) DEFAULT NULL,
  score INT DEFAULT 0,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_exam_id (exam_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='培训成绩';

-- 28. AI决策
CREATE TABLE IF NOT EXISTS ai_decisions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  decision_no VARCHAR(64) DEFAULT NULL,
  scene VARCHAR(256) DEFAULT NULL,
  suggestion TEXT DEFAULT NULL,
  confidence INT DEFAULT 0,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI决策';

-- 29. 智能预警
CREATE TABLE IF NOT EXISTS smart_alerts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  alert_no VARCHAR(64) DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  rule_id BIGINT DEFAULT NULL,
  level INT DEFAULT 1,
  message TEXT DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智能预警';

-- 30. IoT协议/管道/数据点
CREATE TABLE IF NOT EXISTS iot_protocols (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  protocol_name VARCHAR(128) DEFAULT NULL,
  protocol_type VARCHAR(32) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IoT协议';

CREATE TABLE IF NOT EXISTS iot_pipelines (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  pipeline_name VARCHAR(128) DEFAULT NULL,
  source VARCHAR(128) DEFAULT NULL,
  target VARCHAR(128) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IoT数据管道';

CREATE TABLE IF NOT EXISTS iot_data_points (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  point_name VARCHAR(128) DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  data_type VARCHAR(32) DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  config JSON DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IoT数据点';

-- 31. 控制命令模板
CREATE TABLE IF NOT EXISTS control_templates (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  template_name VARCHAR(128) DEFAULT NULL,
  template_type VARCHAR(32) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='控制模板';

-- 32. 地图标记/图层/配置
CREATE TABLE IF NOT EXISTS map_markers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) DEFAULT NULL,
  type VARCHAR(32) DEFAULT NULL,
  lng DECIMAL(10,7) DEFAULT NULL,
  lat DECIMAL(10,7) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地图标记';

CREATE TABLE IF NOT EXISTS map_layers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  layer_name VARCHAR(128) DEFAULT NULL,
  layer_type VARCHAR(32) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地图图层';

CREATE TABLE IF NOT EXISTS map_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  config_name VARCHAR(128) DEFAULT NULL,
  config JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地图配置';

-- 33. 子系统
CREATE TABLE IF NOT EXISTS subsystems (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) DEFAULT NULL,
  type VARCHAR(32) DEFAULT NULL,
  unit_id VARCHAR(64) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='子系统';

CREATE TABLE IF NOT EXISTS subsystem_devices (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  subsystem_id BIGINT DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_subsystem_id (subsystem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='子系统设备';

CREATE TABLE IF NOT EXISTS subsystem_metrics (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  subsystem_id BIGINT DEFAULT NULL,
  metric_name VARCHAR(64) DEFAULT NULL,
  value DECIMAL(10,2) DEFAULT NULL,
  unit VARCHAR(32) DEFAULT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_subsystem_id (subsystem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='子系统指标';

-- 34. 监控日志/视频通道
CREATE TABLE IF NOT EXISTS monitor_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  log_type VARCHAR(32) DEFAULT NULL,
  module VARCHAR(64) DEFAULT NULL,
  message TEXT DEFAULT NULL,
  level VARCHAR(16) DEFAULT 'info',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_level (level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='监控日志';

CREATE TABLE IF NOT EXISTS video_channels (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  channel_name VARCHAR(128) DEFAULT NULL,
  camera_id VARCHAR(64) DEFAULT NULL,
  stream_url VARCHAR(512) DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_camera_id (camera_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频通道';

-- 35. 待办/公告
CREATE TABLE IF NOT EXISTS todos (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  priority INT DEFAULT 1,
  status INT DEFAULT 0,
  user_id VARCHAR(64) DEFAULT NULL,
  due_date DATE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_user_id (user_id), INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='待办';

CREATE TABLE IF NOT EXISTS notices (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(256) DEFAULT NULL,
  content TEXT DEFAULT NULL,
  type VARCHAR(32) DEFAULT 'system',
  priority INT DEFAULT 1,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='公告';

-- 36. 组织架构
CREATE TABLE IF NOT EXISTS departments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) DEFAULT NULL,
  parent_id BIGINT DEFAULT 0,
  leader VARCHAR(64) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  sort_order INT DEFAULT 0,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_parent_id (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织架构';

-- 37. 报警快照
CREATE TABLE IF NOT EXISTS alarm_snapshots (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  alarm_id BIGINT DEFAULT NULL,
  image_url VARCHAR(512) DEFAULT NULL,
  video_url VARCHAR(512) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_alarm_id (alarm_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='报警快照';

-- 38. 消控室配置
CREATE TABLE IF NOT EXISTS control_room_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  unit_id VARCHAR(64) DEFAULT NULL,
  room_name VARCHAR(128) DEFAULT NULL,
  location VARCHAR(256) DEFAULT NULL,
  cameras JSON DEFAULT NULL,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消控室配置';

-- 39. 楼层设备
CREATE TABLE IF NOT EXISTS floor_devices (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  floor_plan_id BIGINT DEFAULT NULL,
  device_id VARCHAR(64) DEFAULT NULL,
  x DECIMAL(10,2) DEFAULT 0,
  y DECIMAL(10,2) DEFAULT 0,
  status INT DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_floor_plan_id (floor_plan_id), INDEX idx_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='楼层设备';

SET FOREIGN_KEY_CHECKS = 1;
