CREATE TABLE IF NOT EXISTS fire_building (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  unit_id VARCHAR(64) NOT NULL DEFAULT 'PENDING',
  name VARCHAR(100) NOT NULL,
  type VARCHAR(50) DEFAULT '商业',
  total_floors INT DEFAULT 1,
  address VARCHAR(255) DEFAULT '',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_unit_id (unit_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='建筑物表';

CREATE TABLE IF NOT EXISTS fire_floor (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  building_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  floor_number INT NOT NULL DEFAULT 0,
  plan_image_url VARCHAR(255) DEFAULT NULL,
  plan_width INT DEFAULT 0,
  plan_height INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_building_id (building_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='楼层表';

CREATE TABLE IF NOT EXISTS fire_floor_device_position (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  floor_id BIGINT UNSIGNED NOT NULL,
  device_id VARCHAR(64) NOT NULL,
  x FLOAT NOT NULL DEFAULT 0,
  y FLOAT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_floor_device (floor_id, device_id),
  INDEX idx_floor_id (floor_id),
  INDEX idx_device_id (device_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='设备点位表';
