-- 修复 users.id (VARCHAR) 与 sys_user_role.user_id (BIGINT) 类型不匹配
-- 方案：将 RBAC 表中的 user_id 改为 VARCHAR(64)，与 users 表保持一致

-- 先删除可能存在的外键约束（兼容旧版 MySQL）
SET @fk1 := (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_user_role' AND CONSTRAINT_TYPE = 'FOREIGN KEY');
SET @sql1 := IF(@fk1 IS NOT NULL, CONCAT('ALTER TABLE sys_user_role DROP FOREIGN KEY ', @fk1), 'SELECT 1');
PREPARE stmt1 FROM @sql1; EXECUTE stmt1; DEALLOCATE PREPARE stmt1;

SET @fk2 := (SELECT CONSTRAINT_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sys_data_scope' AND CONSTRAINT_TYPE = 'FOREIGN KEY');
SET @sql2 := IF(@fk2 IS NOT NULL, CONCAT('ALTER TABLE sys_data_scope DROP FOREIGN KEY ', @fk2), 'SELECT 1');
PREPARE stmt2 FROM @sql2; EXECUTE stmt2; DEALLOCATE PREPARE stmt2;

ALTER TABLE sys_user_role MODIFY user_id VARCHAR(64) NOT NULL COMMENT '用户ID';
ALTER TABLE sys_data_scope MODIFY user_id VARCHAR(64) NOT NULL COMMENT '用户ID';
