import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('124.223.35.58', username='root', password='Zhangcong2255', timeout=30)
stdin, stdout, stderr = client.exec_command('mysql -u root -pZhangcong2255 fire_platform -e "DESCRIBE units" 2>&1')
out = stdout.read().decode('utf-8', errors='replace').strip()
print('=== units table ===')
print(out)
stdin, stdout, stderr = client.exec_command('mysql -u root -pZhangcong2255 fire_platform -e "SELECT id, name FROM units LIMIT 5" 2>&1')
out = stdout.read().decode('utf-8', errors='replace').strip()
print('=== units data ===')
print(out)
client.close()
