import paramiko
client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect('124.223.35.58', username='root', password='Zhangcong2255', timeout=10)
stdin, stdout, stderr = client.exec_command('cat /opt/my-fire-api/app.js')
content = stdout.read().decode('utf-8', errors='replace')
print(content)
print('--- STDERR ---')
print(stderr.read().decode('utf-8', errors='replace'))
client.close()
