/**
 * ═══════════════════════════════════════════════════════════════════
 * 旧体系兼容 API 对象（deprecated：新代码请使用独立 service）
 * ═══════════════════════════════════════════════════════════════════
 */
import { legacyRaw } from '../client';

export const legacyApi = {
  get: legacyRaw.get,
  post: legacyRaw.post,
  put: legacyRaw.put,
  patch: legacyRaw.patch,
  delete: legacyRaw.delete,

  login: (username: string, password: string) =>
    legacyRaw.post<{ accessToken: string; refreshToken: string; user: unknown }>('/auth/login', { username, password }),
  register: (username: string, password: string, realName?: string, phone?: string) =>
    legacyRaw.post('/auth/register', { username, password, realName, phone }),
  profile: () => legacyRaw.get('/auth/profile'),
  updateProfile: (data: unknown) => legacyRaw.put('/auth/profile', data),
  changePassword: (oldPassword: string, newPassword: string) => legacyRaw.put('/auth/password', { oldPassword, newPassword }),

  userList: (params?: Record<string, unknown>) => legacyRaw.get('/users', params),
  createUser: (data: unknown) => legacyRaw.post('/users', data),
  updateUser: (id: number, data: unknown) => legacyRaw.put(`/users/${id}`, data),
  deleteUser: (id: number) => legacyRaw.delete(`/users/${id}`),
  resetPassword: (id: number) => legacyRaw.put(`/users/${id}/reset-password`, {}),

  roleList: () => legacyRaw.get('/roles'),
  createRole: (data: unknown) => legacyRaw.post('/roles', data),
  updateRole: (id: number, data: unknown) => legacyRaw.put(`/roles/${id}`, data),
  deleteRole: (id: number) => legacyRaw.delete(`/roles/${id}`),
  permList: () => legacyRaw.get('/permissions'),

  deptList: () => legacyRaw.get('/departments'),
  createDept: (data: unknown) => legacyRaw.post('/departments', data),
  updateDept: (id: number, data: unknown) => legacyRaw.put(`/departments/${id}`, data),
  deleteDept: (id: number) => legacyRaw.delete(`/departments/${id}`),

  unitList: (params?: Record<string, unknown>) => legacyRaw.get('/units/list', params),
  createUnit: (data: unknown) => legacyRaw.post('/units', data),
  updateUnit: (id: number, data: unknown) => legacyRaw.put(`/units/${id}`, data),
  deleteUnit: (id: number) => legacyRaw.delete(`/units/${id}`),
  unitStats: () => legacyRaw.get('/units/stats'),

  deviceList: (params?: Record<string, unknown>) => legacyRaw.get('/devices', params),
  createDevice: (data: unknown) => legacyRaw.post('/devices', data),
  updateDevice: (id: number, data: unknown) => legacyRaw.put(`/devices/${id}`, data),
  deleteDevice: (id: number) => legacyRaw.delete(`/devices/${id}`),
  deviceStats: () => legacyRaw.get('/devices/stats'),
  deviceTypes: () => legacyRaw.get('/devices/types'),

  alarmList: (params?: Record<string, unknown>) => legacyRaw.get('/alarms', params),
  alarmStats: () => legacyRaw.get('/alarms/stats'),
  alarmRecent: () => legacyRaw.get('/alarms/recent'),
  alarmTrend: (days?: number) => legacyRaw.get('/alarms/trend', { days }),
  confirmAlarm: (id: number) => legacyRaw.put(`/alarms/${id}/confirm`, {}),
  handleAlarm: (id: number, result: string) => legacyRaw.put(`/alarms/${id}/handle`, { handleResult: result }),
  dismissAlarm: (id: number) => legacyRaw.put(`/alarms/${id}/dismiss`, {}),

  maintCompanyList: (params?: Record<string, unknown>) => legacyRaw.get('/maintenance/companies', params),
  createMaintCompany: (data: unknown) => legacyRaw.post('/maintenance/companies', data),
  updateMaintCompany: (id: number, data: unknown) => legacyRaw.put(`/maintenance/companies/${id}`, data),
  deleteMaintCompany: (id: number) => legacyRaw.delete(`/maintenance/companies/${id}`),
  workOrderList: (params?: Record<string, unknown>) => legacyRaw.get('/maintenance/work-orders', params),
  createWorkOrder: (data: unknown) => legacyRaw.post('/maintenance/work-orders', data),
  updateWorkOrder: (id: number, data: unknown) => legacyRaw.put(`/maintenance/work-orders/${id}`, data),
  deleteWorkOrder: (id: number) => legacyRaw.delete(`/maintenance/work-orders/${id}`),
  assignWorkOrder: (id: number, data: unknown) => legacyRaw.put(`/maintenance/work-orders/${id}/assign`, data),
  completeWorkOrder: (id: number, data: unknown) => legacyRaw.put(`/maintenance/work-orders/${id}/complete`, data),
  maintStats: () => legacyRaw.get('/maintenance/stats'),

  patrolPlanList: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/plans', params),
  createPatrolPlan: (data: unknown) => legacyRaw.post('/patrol/plans', data),
  updatePatrolPlan: (id: number, data: unknown) => legacyRaw.put(`/patrol/plans/${id}`, data),
  deletePatrolPlan: (id: number) => legacyRaw.delete(`/patrol/plans/${id}`),
  patrolRecordList: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/records', params),
  createPatrolRecord: (data: unknown) => legacyRaw.post('/patrol/records', data),
  hazardList: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/hazards', params),
  createHazard: (data: unknown) => legacyRaw.post('/patrol/hazards', data),
  updateHazard: (id: number, data: unknown) => legacyRaw.put(`/patrol/hazards/${id}`, data),
  rectifyHazard: (id: number) => legacyRaw.put(`/patrol/hazards/${id}/rectify`, {}),

  getControlRooms: (params?: Record<string, unknown>) => legacyRaw.get('/control-rooms', params),
  getControlRoomDetail: (id: number | string) => legacyRaw.get(`/control-rooms/${id}`),
  createControlRoom: (data: unknown) => legacyRaw.post('/control-rooms', data),
  updateControlRoom: (id: number | string, data: unknown) => legacyRaw.put(`/control-rooms/${id}`, data),
  deleteControlRoom: (id: number | string) => legacyRaw.delete(`/control-rooms/${id}`),
  getControlRoomHosts: (roomId?: number | string) => legacyRaw.get('/control-rooms/hosts', roomId !== undefined ? { roomId } : undefined),
  getControlRoomHostDetail: (id: number) => legacyRaw.get(`/control-rooms/hosts/${id}`),
  createControlRoomHost: (data: unknown) => legacyRaw.post('/control-rooms/hosts', data),
  updateControlRoomHost: (id: number, data: unknown) => legacyRaw.put(`/control-rooms/hosts/${id}`, data),
  deleteControlRoomHost: (id: number) => legacyRaw.delete(`/control-rooms/hosts/${id}`),
  silenceHost: (hostId: number) => legacyRaw.post('/control-rooms/silence', { hostId }),
  resetHost: (hostId: number) => legacyRaw.post('/control-rooms/reset', { hostId }),
  switchHostMode: (hostId: number, mode: 'manual' | 'auto') => legacyRaw.post('/control-rooms/mode', { hostId, mode }),
  controlMultiline: (hostId: number, pointId: number, action: 'start' | 'stop') => legacyRaw.post('/control-rooms/multiline/control', { hostId, pointId, action }),
  controlBus: (hostId: number, pointId: number, action: 'start' | 'stop') => legacyRaw.post('/control-rooms/bus/control', { hostId, pointId, action }),
  getMultilinePanels: (hostId?: number | string) => legacyRaw.get('/control-rooms/multiline', hostId !== undefined ? { hostId } : undefined),
  createMultilinePanel: (data: unknown) => legacyRaw.post('/control-rooms/multiline', data),
  updateMultilinePanel: (id: number, data: unknown) => legacyRaw.put(`/control-rooms/multiline/${id}`, data),
  getBusPoints: (hostId?: number | string, loopNo?: number) => legacyRaw.get('/control-rooms/bus-points', { hostId, loopNo }),
  createBusPoint: (data: unknown) => legacyRaw.post('/control-rooms/bus-points', data),
  updateBusPoint: (id: number, data: unknown) => legacyRaw.put(`/control-rooms/bus-points/${id}`, data),
  getHostCommandLogs: (params?: Record<string, unknown>) => legacyRaw.get('/control-rooms/command-logs', params),
  getRealtimeStatus: (roomId?: number | string, hostId?: number) => legacyRaw.get('/control-rooms/realtime', { roomId, hostId }),
  getShields: (roomId?: number | string, hostId?: number) => legacyRaw.get('/control-rooms/shields', { roomId, hostId }),
  getVideos: (roomId?: number | string) => legacyRaw.get('/control-rooms/videos', { roomId }),
  getHostDeviceCodes: (params?: Record<string, unknown>) => legacyRaw.get('/control-rooms/host-device-codes', params),
  createHostDeviceCode: (data: unknown) => legacyRaw.post('/control-rooms/host-device-codes', data),
  updateHostDeviceCode: (id: number, data: unknown) => legacyRaw.put(`/control-rooms/host-device-codes/${id}`, data),
  deleteHostDeviceCode: (id: number) => legacyRaw.delete(`/control-rooms/host-device-codes/${id}`),
  importHostDeviceCodes: (hostId: string, file: File) => {
    const form = new FormData();
    form.append('file', file);
    form.append('hostId', hostId);
    return legacyRaw.post('/control-rooms/host-device-codes/import', form);
  },

  planList: (params?: Record<string, unknown>) => legacyRaw.get('/plans', params),
  createPlan: (data: unknown) => legacyRaw.post('/plans', data),
  updatePlan: (id: number, data: unknown) => legacyRaw.put(`/plans/${id}`, data),
  deletePlan: (id: number) => legacyRaw.delete(`/plans/${id}`),

  linkageRuleList: (params?: Record<string, unknown>) => legacyRaw.get('/linkage/rules', params),
  createLinkageRule: (data: unknown) => legacyRaw.post('/linkage/rules', data),
  updateLinkageRule: (id: number, data: unknown) => legacyRaw.put(`/linkage/rules/${id}`, data),
  deleteLinkageRule: (id: number) => legacyRaw.delete(`/linkage/rules/${id}`),
  triggerLinkageRule: (id: number) => legacyRaw.post(`/linkage/rules/${id}/trigger`, {}),
  getLinkageRecords: (params?: Record<string, unknown>) => legacyRaw.get('/linkage/records', params),

  drillList: (params?: Record<string, unknown>) => legacyRaw.get('/drills', params),
  createDrill: (data: unknown) => legacyRaw.post('/drills', data),
  updateDrill: (id: number, data: unknown) => legacyRaw.put(`/drills/${id}`, data),
  deleteDrill: (id: number) => legacyRaw.delete(`/drills/${id}`),

  knowledgeList: (params?: Record<string, unknown>) => legacyRaw.get('/knowledge', params),
  createKnowledge: (data: unknown) => legacyRaw.post('/knowledge', data),
  updateKnowledge: (id: number, data: unknown) => legacyRaw.put(`/knowledge/${id}`, data),
  deleteKnowledge: (id: number) => legacyRaw.delete(`/knowledge/${id}`),
  knowledgeCategories: () => legacyRaw.get('/knowledge/categories'),

  iotDeviceList: (params?: Record<string, unknown>) => legacyRaw.get('/iot/devices', params),
  createIotDevice: (data: unknown) => legacyRaw.post('/iot/devices', data),
  updateIotDevice: (id: number, data: unknown) => legacyRaw.put(`/iot/devices/${id}`, data),
  deleteIotDevice: (id: number) => legacyRaw.delete(`/iot/devices/${id}`),
  protocolList: () => legacyRaw.get('/iot/protocols'),
  createProtocol: (data: unknown) => legacyRaw.post('/iot/protocols', data),
  updateProtocol: (id: number, data: unknown) => legacyRaw.put(`/iot/protocols/${id}`, data),
  deleteProtocol: (id: number) => legacyRaw.delete(`/iot/protocols/${id}`),
  pipelineList: () => legacyRaw.get('/iot/pipelines'),
  createPipeline: (data: unknown) => legacyRaw.post('/iot/pipelines', data),

  aiDecisionList: (params?: Record<string, unknown>) => legacyRaw.get('/ai/decisions', params),
  createAiDecision: (data: unknown) => legacyRaw.post('/ai/decisions', data),
  smartAlertList: (params?: Record<string, unknown>) => legacyRaw.get('/ai/alerts', params),
  alertConfirm: (id: number) => legacyRaw.put(`/ai/alerts/${id}/confirm`, {}),
  alertHandle: (id: number) => legacyRaw.put(`/ai/alerts/${id}/handle`, {}),

  courseList: (params?: Record<string, unknown>) => legacyRaw.get('/training/courses', params),
  createCourse: (data: unknown) => legacyRaw.post('/training/courses', data),
  updateCourse: (id: number, data: unknown) => legacyRaw.put(`/training/courses/${id}`, data),
  deleteCourse: (id: number) => legacyRaw.delete(`/training/courses/${id}`),
  examList: (params?: Record<string, unknown>) => legacyRaw.get('/training/exams', params),
  createExam: (data: unknown) => legacyRaw.post('/training/exams', data),

  inspectionList: (params?: Record<string, unknown>) => legacyRaw.get('/inspections', params),
  createInspection: (data: unknown) => legacyRaw.post('/inspections', data),
  updateInspection: (id: number, data: unknown) => legacyRaw.put(`/inspections/${id}`, data),
  deleteInspection: (id: number) => legacyRaw.delete(`/inspections/${id}`),

  configList: () => legacyRaw.get('/system/config'),
  setConfig: (key: string, value: string) => legacyRaw.post('/system/config', { configKey: key, configValue: value }),
  logList: (params?: Record<string, unknown>) => legacyRaw.get('/system/logs', params),
  notifyTemplateList: () => legacyRaw.get('/system/notify-templates'),
  createNotifyTemplate: (data: unknown) => legacyRaw.post('/system/notify-templates', data),
  updateNotifyTemplate: (id: number, data: unknown) => legacyRaw.put(`/system/notify-templates/${id}`, data),
  deleteNotifyTemplate: (id: number) => legacyRaw.delete(`/system/notify-templates/${id}`),
  screenList: () => legacyRaw.get('/system/screens'),
  saveScreen: (data: unknown) => legacyRaw.post('/system/screens', data),
  moduleList: () => legacyRaw.get('/system/modules'),
  toggleModule: (moduleId: string, status: string) => legacyRaw.put('/system/modules/toggle', { moduleId, status }),
  dashboard: () => legacyRaw.get('/system/dashboard'),

  deviceAnalysis: (days?: number) => legacyRaw.get('/analysis/device', { days }),
  alarmAnalysis: (days?: number) => legacyRaw.get('/analysis/alarm', { days }),
  maintenanceAnalysis: () => legacyRaw.get('/analysis/maintenance'),
  hazardAnalysis: () => legacyRaw.get('/analysis/hazard'),
  patrolCompletion: (days?: number) => legacyRaw.get('/analysis/patrol', { days }),

  dailyReport: (date?: string) => legacyRaw.get('/reports/daily', { date }),
  weeklyReport: (endDate?: string) => legacyRaw.get('/reports/weekly', { endDate }),
  monthlyReport: (year?: number, month?: number) => legacyRaw.get('/reports/monthly', { year, month }),
  deviceReport: (unitId?: number) => legacyRaw.get('/reports/device', { unitId }),
  maintenanceReport: (startDate?: string, endDate?: string) => legacyRaw.get('/reports/maintenance', { startDate, endDate }),
  patrolReport: (startDate?: string, endDate?: string) => legacyRaw.get('/reports/patrol', { startDate, endDate }),

  gisPoints: () => legacyRaw.get('/gis/points'),
  gisSituation: () => legacyRaw.get('/gis/situation'),
  gisAlarmPoints: () => legacyRaw.get('/gis/alarm-points'),

  monitorOverview: () => legacyRaw.get('/monitor/overview'),

  bigScreen: () => legacyRaw.get('/bigscreen/data'),

  workbench: () => legacyRaw.get('/workbench'),

  dutySchedules: () => legacyRaw.get('/duty/schedules'),
  dutyLogs: (params?: Record<string, unknown>) => legacyRaw.get('/duty/logs', params),
  dutyCurrent: () => legacyRaw.get('/duty/current'),

  getUsers: (params?: Record<string, unknown>) => legacyRaw.get('/users', params),
  getRoles: () => legacyRaw.get('/roles'),
  getOrgs: () => legacyRaw.get('/departments'),
  getLoginLogs: (params?: Record<string, unknown>) => legacyRaw.get('/system/logs', params),
  getUnits: (params?: Record<string, unknown>) => legacyRaw.get('/units/list', params),
  getDevices: (params?: Record<string, unknown>) => legacyRaw.get('/devices', params),
  getDeviceTypes: () => legacyRaw.get('/devices/types'),
  getDashboardStats: () => legacyRaw.get('/system/dashboard'),
  getPatrolPlans: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/plans', params),
  getPatrolTasks: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/records', params),
  getHazards: (params?: Record<string, unknown>) => legacyRaw.get('/patrol/hazards', params),
  getPreplans: (params?: Record<string, unknown>) => legacyRaw.get('/plans', params),
  getPlanRecords: (params?: Record<string, unknown>) => legacyRaw.get('/drills', params),
  getAlarmStatistics: () => legacyRaw.get('/alarms/stats'),
  getFaultAlarms: (unitId?: number | string) => legacyRaw.get('/alarms', { alarmType: 2, pageSize: 50, ...(unitId !== undefined && unitId !== '' ? { unitId } : {}) }),
  getFireAlarms: (unitId?: number | string) => legacyRaw.get('/alarms', { alarmType: 1, pageSize: 50, ...(unitId !== undefined && unitId !== '' ? { unitId } : {}) }),
  getFeedbackAlarms: () => legacyRaw.get('/alarms', { status: 3, pageSize: 50 }),
  confirmFireAlarm: (id: number) => legacyRaw.put(`/alarms/${id}/confirm`, {}),
  handleFault: (id: number, result: string) => legacyRaw.put(`/alarms/${id}/handle`, { handleResult: result }),
  silenceConfirm: (data: unknown) => legacyRaw.post('/control-rooms/silence', data),
  resetConfirm: (data: unknown) => legacyRaw.post('/control-rooms/reset', data),
  switchMode: (data: unknown) => legacyRaw.post('/control-rooms/mode', data),
  addShield: (data: unknown) => legacyRaw.post('/control-rooms/shield', data),
};
